### ISSUE TITLE
Have an answer for adding new formats

### ISSUE THREAD

**Issue by gwyneplaine** [gwyneplaine/tokens-distribution-spike#19]
Adding new formats is at the moment a reasonably complicated procedure. The following questions need answers before we can deprecate this repo in favor of the new repo in the @atlassian org

1. Do we need to simplify this workflow / partially automate it for milestone 1? 
2. If yes, what will the simplified workflow be.

**Comment by allardvanhelbergen** [comment]
moved to jira
