### ISSUE TITLE
Finalise CI/CD workflow

### ISSUE THREAD

**Issue by gwyneplaine** [gwyneplaine/tokens-distribution-spike#21]
# Current State 

At the moment our workflow is as follows: 
- User commits change 
- User commits change-set documenting change and intended version bump 
- User submits PR 
- CircleCI validates changes (unit tests and possibly other things) 
- PR is merged into master
- CircleCI validates changes on master 
- CircleCI:
  - builds packages, 
  - bumps versions of relevant packages 
  - commits new version and change logs 
  - publishes packages 
  - pushes changes back to master 
  - [we probably want a release tag as well for each package] (optional)

# Remaining questions
## Build Version and publish a single format?
- Do we want to enable building of specific individual formats (such that design-tokens-js gets built, versioned and published and no the packages in the workspace are touched)?

## Build step outside of CI
Right now user has to know what packages will be built / changed *_ahead_* of the build step, as the build step happens on CI while the changeset needs to be run locally. 

Should the build step be pushed as a responsibility of the developer? If yes, then we should remove the workspaces from the .gitignore file and set up some sort of tooling for ensuring the integrity of the build files (such that non-programatic and unintended changes to the build are caught before the PR gets merged). 

What will this tooling look like? Is this something we should be concerned with in milestone 1?

**Comment by sarahbethfederman** [comment]
For your first question, I'd say maybe not per package but per platform? I can't imagine a situation in the near future where we'd need to only change only css, but I can imagine needing to fix a transform for "web" or something similar. Not a super high priority atm. 

For the CI step, I might be misunderstanding
- User submits PR
- CircleCI validates changes (unit tests and possibly other things)
- PR is merged into master
- CircleCI validates changes on master
Shouldn't the proposed changes be tested on master before they're merged? So we don't have to rollback if we end up running regression tests and they fail?

**Comment by gwyneplaine** [comment]
As discussed offline, it seems more prudent for us to initially keep publishing and versioning a manual step on master. atlaskit/build-releases provides enough automation for versioning and publishing multiple packages to make manually running `version` and `publish` in updated local versions of master very straightforward. 

This can be extended in the future to be fully automated via CI/CD in future milestones.

**Comment by allardvanhelbergen** [comment]
Moved to jira.
